### ISSUE TITLE
[Feature Request] 希望能改成AndroidX

### ISSUE THREAD

**Issue by Haocen2004** [ahuyangdong/QrCodeLib#1]
本人 android 开发初学者，新版Android Studio默认使用AndroidX导致在引用该项目时报错找不到v7包，小白东改改西改改还是报错，希望能给一个改好Androidx的版本

**Comment by ahuyangdong** [comment]
很好的建议，谢谢，不过我暂时还未使用androidx，后续有时间我来整整

**Comment by ahuyangdong** [comment]
androidx版本分支已构建：https://github.com/ahuyangdong/QrCodeLib/tree/androidx

> 本人 android 开发初学者，新版Android Studio默认使用AndroidX导致在引用该项目时报错找不到v7包，小白东改改西改改还是报错，希望能给一个改好Androidx的版本
